### ISSUE TITLE
Original word not returned properly

### ISSUE THREAD

**Issue by akhilesh1311** [novel/py-urbandict#11]
`import urbandict`
`urbandict.define('anal')`
[{'word': 'anal sex',
  'def': 'What to avoid in prison.',
  'example': 'After dropping my soap, I just let it be so as not to incite an anal rampage.'},
 {'word': 'Anal unknown',
  'def': 'When a crotch rocket enters the caverns of life.',
  'example': 'Sarah to Doug "Will you please take the damn trash out?"Doug "Na playin Fortnite"Sarah "I\'ll give you Anal!"Doug "ON IT!" (Rockets off Couch)'},
 {'word': 'Anal sex',
  'def': 'its like having a dick in your ass',
  'example': "i've never tried anal...whats it like? it's like having a dick in your ass"},
 {'word': 'Anal unknown',
  'def': 'Something that may happen when you are trying to lose your virginity but you are too tight and it slips in the wrong hole',
  'example': "We couldn't get it in and it slipped causing me to scream wrong hole, and that's the first time I did anal"},
 {'word': 'anal sex',
  'def': 'Butt sex',
  'example': 'Miranda is well known for her wild anal nights.'},
 {'word': 'An al unknown',
  'def': 'The act of stealing someone else’s mc donalds by accident, going bright red, and blaming it on ur friends who then have to go and get ur meal for you incase you get in trouble',
  'example': 'Ah shit that guy is pulling an An Al'},
 {'word': 'anal sex',
  'def': "bend over and  i'll show you.",
  'example': '^ what he said ^'}]

It shouldn't return the word as 'anal unknown' or 'anal sex'. 
BTW, I think unknown/sex returned is actually a tag associated with the word. Like, 'anal' word has 'sex' tag associated with in red besides it in a few definitions. Probably we can return a separate dictionary mapping for it?

**Comment by novel** [comment]
Apparently, 'category' is a relatively new thing (or I managed to not notice it for quite some time).

I've created a branch with an initial support. Should give it a little more testing. Not sure if there could be words with multiple categories, I didn't find such...

**Comment by novel** [comment]
This should be fixed now.

**Comment by akhilesh1311** [comment]
Awesome! Thanks @novel .
