### ISSUE TITLE
please push tag0.2 to master branch, and push that to pip, so the master also works with python2.7

### ISSUE THREAD

**Issue by tverrbjelke** [novel/py-urbandict#3]
1) I did this: with pyhton 2.7  
> pip install py-urbandict 
installs version 0.1 (not working)

2) I cloned the master, https://github.com/novel/py-urbandict and installed it manually by copying the .py files over the installed version  0.1

3) Saw that your master setup.py says still 0.1, but already including the 2.7 fixes

4) saw that in setup.py is also dependency missing: urllib (and for python 3.X the subpackages?)
So maybe you get that dependency fixed and merge that into the master?

cheers, tverrbjelke

**Comment by novel** [comment]
Should be fine now.
