### ISSUE TITLE
Change licence to Unlicense

### ISSUE THREAD

**Issue by novel** [novel/py-urbandict#8]
Currently there's no license for the py-urbandict project. I was assuming that means that this code is public domain in this case, but it turns out that I'm wrong. As this is a really trivial piece of code, I just want to make it easy for people to use it whatever they want.

For this purpose I'm considering to license it under the 'Unlicense' http://unlicense.org/.

I'm adding all the committers here. Please response 'OK' if you agree or share your objections if you have any.

@notuxic @Kami @sumeet @YorikSar 

Thanks,
Roman

**Comment by sumeet** [comment]
no objections here!

OK

On Monday, January 4, 2016, Roman Bogorodskiy <notifications@github.com>
wrote:

> Currently there's no license for the py-urbandict project. I was assuming
> that means that this code is public domain in this case, but it turns out
> that I'm wrong. As this is a really trivial piece of code, I just want to
> make it easy for people to use it whatever they want.
>
> For this purpose I'm considering to license it under the 'Unlicense'
> http://unlicense.org/.
>
> I'm adding all the committers here. Please response 'OK' if you agree or
> share your objections if you have any.
>
> @notuxic <https://github.com/notuxic> @Kami <https://github.com/Kami>
> @sumeet <https://github.com/sumeet> @YorikSar
> <https://github.com/YorikSar>
>
> Thanks,
> Roman
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/novel/py-urbandict/issues/8>.
>


-- 
Sumeet Agarwal
937.657.8614

**Comment by notuxic** [comment]
Ok

**Comment by Kami** [comment]
I'm fine with that.

**Comment by YorikSar** [comment]
OK

**Comment by novel** [comment]
Thank you, guys, I really did not expect you'll response that fast!

Along with the COPYING file, I've added the CONTRIBUTORS file with links to your github accounts. If you'd like to change the way you're displayed here, please send your pull requests.

Thanks again,
Roman
